include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "test/.test_coverage.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error

linter:
  rules:
    avoid_implementing_value_types: false
